version: '3'
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    ports:
      - 3210:3210
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ACCESS_CODE: ${ACCESS_CODE}
    restart: always
